### ISSUE TITLE
[FEAT] OpenAI GPT-3를 이용한 chatbot 만들기

### ISSUE THREAD

**Issue by GaYeongLee0419** [Dr-CheopCheop/ZIP-COOK_Server#2]
## ISSUE
- "오늘 날씨에 어울리는 음식을 추천해줘", "김치찌개 레시피를 알려줘" 등의 질문을 했을 때 그에 따른 적절한 답변을 제공해주는 chatbot이다.

## TO-DO
- [ ] OpenAI API Test
- [x] OpenAI GPT-3를 이용한 chatbot 제작
- [x] Chatbot 첫 페이지에 계절 음식 보여주기
